image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:    
    - cd hugo-documentacion
    - hugo

pages:
  script:   
    - cd hugo-documentacion
    - hugo
    - cp -R public ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
