image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - deploy

deploy:
  stage: deploy
  script:   
    - cd hugo-documentacion
    - hugo --destination ../public
  artifacts:
    paths:
      - public
  only:
    - master
